name: Build and test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os:
          [
            ubuntu-latest,
            ubuntu-24.04-arm,
            windows-latest,
            windows-11-arm,
            macos-latest
          ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - run: npm ci
      - run: npm run format-check
        if: ${{ runner.os != 'Windows' }}
      - run: npm run lint
      - run: npm run build
      - run: npm run test
      - run: npm audit --audit-level=high
  test:
    strategy:
      matrix:
        os:
          [
            ubuntu-latest,
            ubuntu-24.04-arm,
            windows-latest,
            windows-11-arm,
            macos-latest
          ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
          targets: x86_64-apple-ios, armv7-unknown-linux-musleabi
